/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AccessControlFaucet__factory } from "./AccessControlFaucet__factory";
export { Diamond__factory } from "./Diamond__factory";
export { DiamondInit__factory } from "./DiamondInit__factory";
export { DiamondLoupeFaucet__factory } from "./DiamondLoupeFaucet__factory";
export { ERC20__factory } from "./ERC20__factory";
export { ERC20Token__factory } from "./ERC20Token__factory";
export { IAccessControl__factory } from "./IAccessControl__factory";
export { IDiamondCut__factory } from "./IDiamondCut__factory";
export { IDiamondLoupe__factory } from "./IDiamondLoupe__factory";
export { IERC165__factory } from "./IERC165__factory";
export { IERC20__factory } from "./IERC20__factory";
export { IERC20Metadata__factory } from "./IERC20Metadata__factory";
export { IMedicOperationsFaucet__factory } from "./IMedicOperationsFaucet__factory";
export { IOwnerOperationsFaucet__factory } from "./IOwnerOperationsFaucet__factory";
export { IPacientOperationsFaucet__factory } from "./IPacientOperationsFaucet__factory";
export { LibAccessControlStorage__factory } from "./LibAccessControlStorage__factory";
export { LibDiamond__factory } from "./LibDiamond__factory";
export { LibMedicalStorage__factory } from "./LibMedicalStorage__factory";
export { LibStructStorage__factory } from "./LibStructStorage__factory";
export { MedicOperationsFaucet__factory } from "./MedicOperationsFaucet__factory";
export { OwnerOperationsFaucet__factory } from "./OwnerOperationsFaucet__factory";
export { PacientOperationsFaucet__factory } from "./PacientOperationsFaucet__factory";
