/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOwnerOperationsFaucet,
  IOwnerOperationsFaucetInterface,
} from "../IOwnerOperationsFaucet";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "medic",
        type: "address",
      },
    ],
    name: "MedicAccountAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "medic",
        type: "address",
      },
    ],
    name: "MedicAccountRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "medic",
        type: "address",
      },
    ],
    name: "addMedic",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "initializeOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "medic",
        type: "address",
      },
    ],
    name: "removeMedic",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOwnerOperationsFaucet__factory {
  static readonly abi = _abi;
  static createInterface(): IOwnerOperationsFaucetInterface {
    return new Interface(_abi) as IOwnerOperationsFaucetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOwnerOperationsFaucet {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IOwnerOperationsFaucet;
  }
}
