/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPacientOperationsFaucet,
  IPacientOperationsFaucetInterface,
} from "../IPacientOperationsFaucet";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    name: "PacientRegistered",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "pacientHash",
        type: "string",
      },
    ],
    name: "getMedics",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "medic",
        type: "address",
      },
      {
        internalType: "string",
        name: "pacientHash",
        type: "string",
      },
    ],
    name: "getReportsFromMedic",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "reportCID",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
        ],
        internalType: "struct LibMedicalStorage.MedicalReport[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "pacientHash",
        type: "string",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPacientOperationsFaucet__factory {
  static readonly abi = _abi;
  static createInterface(): IPacientOperationsFaucetInterface {
    return new Interface(_abi) as IPacientOperationsFaucetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPacientOperationsFaucet {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPacientOperationsFaucet;
  }
}
