/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  LibAccessControlStorage,
  LibAccessControlStorageInterface,
} from "../LibAccessControlStorage";

const _abi = [
  {
    inputs: [],
    name: "ACCESS_CONTROL_STORAGE_SLOT",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class LibAccessControlStorage__factory {
  static readonly abi = _abi;
  static createInterface(): LibAccessControlStorageInterface {
    return new Interface(_abi) as LibAccessControlStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): LibAccessControlStorage {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as LibAccessControlStorage;
  }
}
