/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  LibMedicalStorage,
  LibMedicalStorageInterface,
} from "../LibMedicalStorage";

const _abi = [
  {
    inputs: [],
    name: "MEDICAL_STORAGE_SLOT",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class LibMedicalStorage__factory {
  static readonly abi = _abi;
  static createInterface(): LibMedicalStorageInterface {
    return new Interface(_abi) as LibMedicalStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): LibMedicalStorage {
    return new Contract(address, _abi, runner) as unknown as LibMedicalStorage;
  }
}
