/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LibMedicalStorage {
  export type MedicalReportStruct = {
    reportCID: string;
    timestamp: BigNumberish;
  };

  export type MedicalReportStructOutput = [
    reportCID: string,
    timestamp: bigint
  ] & { reportCID: string; timestamp: bigint };
}

export interface IMedicOperationsFaucetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "medicAddReport"
      | "medicGetReportHash"
      | "medicGetReportsForPacient"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MedicAddedReport"): EventFragment;

  encodeFunctionData(
    functionFragment: "medicAddReport",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "medicGetReportHash",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "medicGetReportsForPacient",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "medicAddReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "medicGetReportHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "medicGetReportsForPacient",
    data: BytesLike
  ): Result;
}

export namespace MedicAddedReportEvent {
  export type InputTuple = [arg0: boolean];
  export type OutputTuple = [arg0: boolean];
  export interface OutputObject {
    arg0: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IMedicOperationsFaucet extends BaseContract {
  connect(runner?: ContractRunner | null): IMedicOperationsFaucet;
  waitForDeployment(): Promise<this>;

  interface: IMedicOperationsFaucetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  medicAddReport: TypedContractMethod<
    [pacientHash: string, reportHash: string],
    [bigint],
    "nonpayable"
  >;

  medicGetReportHash: TypedContractMethod<
    [pacientHash: string, reportNumber: BigNumberish],
    [string],
    "view"
  >;

  medicGetReportsForPacient: TypedContractMethod<
    [pacientHash: string],
    [LibMedicalStorage.MedicalReportStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "medicAddReport"
  ): TypedContractMethod<
    [pacientHash: string, reportHash: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "medicGetReportHash"
  ): TypedContractMethod<
    [pacientHash: string, reportNumber: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "medicGetReportsForPacient"
  ): TypedContractMethod<
    [pacientHash: string],
    [LibMedicalStorage.MedicalReportStructOutput[]],
    "view"
  >;

  getEvent(
    key: "MedicAddedReport"
  ): TypedContractEvent<
    MedicAddedReportEvent.InputTuple,
    MedicAddedReportEvent.OutputTuple,
    MedicAddedReportEvent.OutputObject
  >;

  filters: {
    "MedicAddedReport(bool)": TypedContractEvent<
      MedicAddedReportEvent.InputTuple,
      MedicAddedReportEvent.OutputTuple,
      MedicAddedReportEvent.OutputObject
    >;
    MedicAddedReport: TypedContractEvent<
      MedicAddedReportEvent.InputTuple,
      MedicAddedReportEvent.OutputTuple,
      MedicAddedReportEvent.OutputObject
    >;
  };
}
