/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IOwnerOperationsFaucetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMedic"
      | "initializeOwnership"
      | "removeMedic"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MedicAccountAdded"
      | "MedicAccountRemoved"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMedic",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeMedic",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addMedic", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMedic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MedicAccountAddedEvent {
  export type InputTuple = [medic: AddressLike];
  export type OutputTuple = [medic: string];
  export interface OutputObject {
    medic: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MedicAccountRemovedEvent {
  export type InputTuple = [medic: AddressLike];
  export type OutputTuple = [medic: string];
  export interface OutputObject {
    medic: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IOwnerOperationsFaucet extends BaseContract {
  connect(runner?: ContractRunner | null): IOwnerOperationsFaucet;
  waitForDeployment(): Promise<this>;

  interface: IOwnerOperationsFaucetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMedic: TypedContractMethod<[medic: AddressLike], [void], "nonpayable">;

  initializeOwnership: TypedContractMethod<[], [void], "nonpayable">;

  removeMedic: TypedContractMethod<[medic: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMedic"
  ): TypedContractMethod<[medic: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeMedic"
  ): TypedContractMethod<[medic: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MedicAccountAdded"
  ): TypedContractEvent<
    MedicAccountAddedEvent.InputTuple,
    MedicAccountAddedEvent.OutputTuple,
    MedicAccountAddedEvent.OutputObject
  >;
  getEvent(
    key: "MedicAccountRemoved"
  ): TypedContractEvent<
    MedicAccountRemovedEvent.InputTuple,
    MedicAccountRemovedEvent.OutputTuple,
    MedicAccountRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "MedicAccountAdded(address)": TypedContractEvent<
      MedicAccountAddedEvent.InputTuple,
      MedicAccountAddedEvent.OutputTuple,
      MedicAccountAddedEvent.OutputObject
    >;
    MedicAccountAdded: TypedContractEvent<
      MedicAccountAddedEvent.InputTuple,
      MedicAccountAddedEvent.OutputTuple,
      MedicAccountAddedEvent.OutputObject
    >;

    "MedicAccountRemoved(address)": TypedContractEvent<
      MedicAccountRemovedEvent.InputTuple,
      MedicAccountRemovedEvent.OutputTuple,
      MedicAccountRemovedEvent.OutputObject
    >;
    MedicAccountRemoved: TypedContractEvent<
      MedicAccountRemovedEvent.InputTuple,
      MedicAccountRemovedEvent.OutputTuple,
      MedicAccountRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
