/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LibMedicalStorage {
  export type MedicalReportStruct = {
    reportCID: string;
    timestamp: BigNumberish;
  };

  export type MedicalReportStructOutput = [
    reportCID: string,
    timestamp: bigint
  ] & { reportCID: string; timestamp: bigint };
}

export interface IPacientOperationsFaucetInterface extends Interface {
  getFunction(
    nameOrSignature: "getMedics" | "getReportsFromMedic" | "register"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PacientRegistered"): EventFragment;

  encodeFunctionData(functionFragment: "getMedics", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getReportsFromMedic",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "register", values: [string]): string;

  decodeFunctionResult(functionFragment: "getMedics", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReportsFromMedic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
}

export namespace PacientRegisteredEvent {
  export type InputTuple = [arg0: AddressLike, arg1: string];
  export type OutputTuple = [arg0: string, arg1: string];
  export interface OutputObject {
    arg0: string;
    arg1: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPacientOperationsFaucet extends BaseContract {
  connect(runner?: ContractRunner | null): IPacientOperationsFaucet;
  waitForDeployment(): Promise<this>;

  interface: IPacientOperationsFaucetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMedics: TypedContractMethod<[pacientHash: string], [string[]], "view">;

  getReportsFromMedic: TypedContractMethod<
    [medic: AddressLike, pacientHash: string],
    [LibMedicalStorage.MedicalReportStructOutput[]],
    "view"
  >;

  register: TypedContractMethod<[pacientHash: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMedics"
  ): TypedContractMethod<[pacientHash: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "getReportsFromMedic"
  ): TypedContractMethod<
    [medic: AddressLike, pacientHash: string],
    [LibMedicalStorage.MedicalReportStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[pacientHash: string], [void], "nonpayable">;

  getEvent(
    key: "PacientRegistered"
  ): TypedContractEvent<
    PacientRegisteredEvent.InputTuple,
    PacientRegisteredEvent.OutputTuple,
    PacientRegisteredEvent.OutputObject
  >;

  filters: {
    "PacientRegistered(address,string)": TypedContractEvent<
      PacientRegisteredEvent.InputTuple,
      PacientRegisteredEvent.OutputTuple,
      PacientRegisteredEvent.OutputObject
    >;
    PacientRegistered: TypedContractEvent<
      PacientRegisteredEvent.InputTuple,
      PacientRegisteredEvent.OutputTuple,
      PacientRegisteredEvent.OutputObject
    >;
  };
}
