/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LibStructStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "INVALID_MEDIC_ADDRESS"
      | "INVALID_OWNER_ADDRESS"
      | "MEDIC_ALREADY_EXISTS"
      | "MEDIC_DOES_NOT_EXIST"
      | "MEDIC_ROLE"
      | "OWNER_ROLE"
      | "PACIENT_ALREADY_EXISTS"
      | "SHOULD_BE_END_USER"
      | "SHOULD_BE_MEDIC"
      | "SHOULD_BE_OWNER"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "INVALID_MEDIC_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_OWNER_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MEDIC_ALREADY_EXISTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MEDIC_DOES_NOT_EXIST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MEDIC_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OWNER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PACIENT_ALREADY_EXISTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHOULD_BE_END_USER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHOULD_BE_MEDIC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHOULD_BE_OWNER",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "INVALID_MEDIC_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_OWNER_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MEDIC_ALREADY_EXISTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MEDIC_DOES_NOT_EXIST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MEDIC_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "OWNER_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PACIENT_ALREADY_EXISTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SHOULD_BE_END_USER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SHOULD_BE_MEDIC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SHOULD_BE_OWNER",
    data: BytesLike
  ): Result;
}

export interface LibStructStorage extends BaseContract {
  connect(runner?: ContractRunner | null): LibStructStorage;
  waitForDeployment(): Promise<this>;

  interface: LibStructStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  INVALID_MEDIC_ADDRESS: TypedContractMethod<[], [string], "view">;

  INVALID_OWNER_ADDRESS: TypedContractMethod<[], [string], "view">;

  MEDIC_ALREADY_EXISTS: TypedContractMethod<[], [string], "view">;

  MEDIC_DOES_NOT_EXIST: TypedContractMethod<[], [string], "view">;

  MEDIC_ROLE: TypedContractMethod<[], [string], "view">;

  OWNER_ROLE: TypedContractMethod<[], [string], "view">;

  PACIENT_ALREADY_EXISTS: TypedContractMethod<[], [string], "view">;

  SHOULD_BE_END_USER: TypedContractMethod<[], [string], "view">;

  SHOULD_BE_MEDIC: TypedContractMethod<[], [string], "view">;

  SHOULD_BE_OWNER: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "INVALID_MEDIC_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_OWNER_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MEDIC_ALREADY_EXISTS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MEDIC_DOES_NOT_EXIST"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MEDIC_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OWNER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PACIENT_ALREADY_EXISTS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SHOULD_BE_END_USER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SHOULD_BE_MEDIC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SHOULD_BE_OWNER"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
